name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: poetry-${{ runner.os }}-

      - name: Install deps
        run: |
          poetry install --no-interaction --no-ansi
          poetry run playwright install --with-deps

      - name: Lint
        run: |
          poetry run ruff check .
          poetry run black --check .

      - name: Run tests (headless)
        run: poetry run pytest -n auto --maxfail=1 --dist=loadfile -q
